---
- name: Hard set the hostname
  hostname: name={{ ipaserver_fqdn }}

- name: Add host entry
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }} "
    line="{{ ansible_default_ipv4.address }}    {{ ipaserver_fqdn }} {{ipaserver_hostname }}"
    owner=root
    group=root
    mode=0644
    state=present

- name: Ensure software is installed (yum)
  yum: name={{ item }} state=present
  with_items: "{{ ipaserver_packages }}"
  when: ansible_distribution == "CentOS" or
        (ansible_distribution == "Fedora" and ansible_distribution_version|int <= 21)

- name: Ensure software is installed (dnf)
  dnf: name={{ item }} state=present
  with_items: "{{ ipaserver_packages }}"
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int > 21

- name: Run the installer
  action: command
    {{ ipaserver_base_command }}
    -U
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    -r {{ ipaserver_realm }}
    -n {{ ipaserver_domain }}
    -a {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    --hostname={{ ipaserver_fqdn }}
    --ip-address={{ ansible_default_ipv4.address }}
    {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }}
    {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }}
    {{ '--forwarder=%s' % ipaserver_dns_forwarder if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
    {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
    {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
    {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
    {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}
    creates=/etc/ipa/default.conf

- include: firewalld.yml
  when: ipaserver_manage_firewalld

- name: Setup SCEP - Disable deferOnFailure
  lineinfile:
    dest: /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
    regexp: "^auths.instance.flatFileAuth.deferOnFailure"
    line: "auths.instance.flatFileAuth.deferOnFailure=true"
    state: present

- name: Setup SCEP - Disable deferOnFailure
  lineinfile:
    dest: /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
    regexp: "^ca.scep.enable"
    line: "ca.scep.enable=true"
    state: present

- name: Setup SCEP - Disable deferOnFailure
  lineinfile:
    dest: /var/lib/pki/pki-tomcat/ca/conf/CS.cfg
    regexp: "^ca.scep.allowedEncryptionAlgorithms"
    line: "ca.scep.allowedEncryptionAlgorithms=DES,DES3"
    state: present

- name: Setup SCEP - Disable deferOnFailure
  blockinfile:
    dest: /var/lib/pki/pki-tomcat/ca/conf/flatfile.txt
    state: present
    block: |
      UID:192.168.1.15
      PWD:password

- name: Restart PKI Service
  service:
    name: pki-tomcatd@pki-tomcat.service
    state: restarted

